# Generated by Django 4.2.30 on 2026-07-22 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='id',
        ),
        migrations.AddField(
            model_name='files',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='spaces.resource'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_video', to='spaces.resource'),
        ),
    ]
