# Generated by Django 4.2.30 on 2026-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_files_id_files_file_id_alter_files_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
    ]
