# Generated by Django 4.2.30 on 2026-07-22 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0002_remove_files_id_files_file_id_alter_files_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('collection_name', models.CharField(max_length=100)),
                ('tanscript', models.JSONField()),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourseQuizes',
            fields=[
                ('content', models.JSONField()),
                ('type', models.CharField(choices=[('easy', 'EASY  '), ('medium', 'MEDIUM'), ('hard', 'HARD')], default='easy', max_length=20)),
                ('quiz_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='spaces.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='spaces.resource')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.files')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCards',
            fields=[
                ('flashcard_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='spaces.resource')),
            ],
        ),
    ]
