# Generated by Django 4.2.30 on 2026-07-23 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_files_id_files_file_id_alter_files_resource_and_more'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='spaces.resource')),
            ],
        ),
    ]
