# Generated by Django 4.2.30 on 2026-07-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_files_id_files_file_id_alter_files_resource_and_more'),
        ('ai', '0002_generationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='title',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generationjob',
            name='type',
            field=models.CharField(choices=[('notes', 'Notes'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard')], default='notes', max_length=20),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resoursequizes',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='spaces.resource'),
        ),
    ]
