# Generated by Django 4.2.30 on 2026-07-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_files_id_files_file_id_alter_files_resource_and_more'),
        ('ai', '0003_flashcards_title_generationjob_type_notes_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChatSession',
            fields=[
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_chat_sessions', serialize=False, to='spaces.resource')),
                ('thread_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
