# Generated by Django 4.2.30 on 2026-07-25 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_files_id_files_file_id_alter_files_resource_and_more'),
        ('ai', '0004_videochatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleQuizes',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('type', models.CharField(choices=[('easy', 'EASY  '), ('medium', 'MEDIUM'), ('hard', 'HARD')], default='easy', max_length=20)),
                ('quiz_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='spaces.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleNotes',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='spaces.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleGenerationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('notes', 'Notes'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard')], default='notes', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='spaces.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFlashcards',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('flashcard_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='spaces.module')),
            ],
        ),
    ]
