# Generated by Django 4.2.30 on 2026-07-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_modulequizes_modulenotes_modulegenerationjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleQuizAttempt',
            fields=[
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attempt', serialize=False, to='ai.modulequizes')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('user_answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceQuizAttempt',
            fields=[
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attempt', serialize=False, to='ai.resoursequizes')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('user_answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20)),
            ],
        ),
    ]
