# Generated by Django 4.2.30 on 2026-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_modulequizattempt_resourcequizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleflashcards',
            name='credit_cost',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='modulequizes',
            name='credit_cost',
            field=models.IntegerField(default=10),
        ),
    ]
