# Generated by Django 4.2.30 on 2026-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_moduleflashcards_credit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexvideos',
            name='final_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
