# Generated by Django 4.2.30 on 2026-07-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_indexvideos_final_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpdfs',
            name='final_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
