# Generated by Django 4.2.30 on 2026-07-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_indexpdfs_final_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexvideos',
            old_name='tanscript',
            new_name='transcript',
        ),
    ]
