# Generated by Django 4.2.30 on 2026-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttags',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
