# Generated by Django 4.2.30 on 2026-07-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_creditwallet_user'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway_order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='creditusage',
            name='user',
        ),
        migrations.AddField(
            model_name='creditusage',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=20),
        ),
        migrations.AddField(
            model_name='creditusage',
            name='wallet',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='accounts.creditwallet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CreditAddTransaction',
        ),
    ]
